"""
Claims verification pack — the judge-proofing artifact.

OWNER: Dev 4 (Platform, Verification & QA)

Every number quoted in PROGRESS.md, the README, and eventually the deck needs
to be reproducible on demand, in one run, by someone who was not in the room
when it was computed. This is that script.

Run:  python scripts/verify_claims.py
Exit: 0 if all claims pass, non-zero if any fail.
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

# Ensure src/ is on the path
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))


# --------------------------------------------------------------------------
# Hardcoded expectations — the source of truth for every claim
# --------------------------------------------------------------------------
CLAIMS = [
    # (claim, expected, actual_fn, tolerance, exact)
    # exact=True means the value must match exactly (for deterministic rules)
    # exact=False means tolerance is used
]


def build_claims():
    """Build the claims table after loading data and models (lazy)."""
    from features import build_feature_matrix, FEATURE_COLUMNS
    from validate_rules import score_mode
    from rules_engine import assess, check_all, verified_root_cause, EXACT_MODES
    from predict import Engine
    import pandas as pd

    _, _, df = build_feature_matrix()
    engine = Engine()

    claims = []

    # --- Dataset claims ---
    claims.append(("Dataset rows", 10_000, len(df), 0, True))
    claims.append(("Total failures", 339, int(df["machine_failure"].sum()), 0, True))
    claims.append(("TWF count", 46, int(df["twf"].sum()), 0, True))
    claims.append(("HDF count", 115, int(df["hdf"].sum()), 0, True))
    claims.append(("PWF count", 95, int(df["pwf"].sum()), 0, True))
    claims.append(("OSF count", 98, int(df["osf"].sum()), 0, True))
    claims.append(("RNF count", 19, int(df["rnf"].sum()), 0, True))

    # --- Model metrics (from docs/model_metrics.json) ---
    metrics_path = REPO_ROOT / "docs" / "model_metrics.json"
    if metrics_path.exists():
        with open(metrics_path) as f:
            metrics = json.load(f)

        fm = metrics["failure_model"]
        claims.append(("PR-AUC", 0.870, fm["pr_auc"], 0.03, False))
        claims.append(("Recall @ tuned threshold", 0.85, fm["recall"], 0.03, False))
        claims.append(("Precision @ tuned threshold", 0.747, fm["precision"], 0.05, False))
        claims.append(("Tuned threshold", 0.249, fm["tuned_threshold"], 0.05, False))

    # --- Rules validation ---
    for mode in ["HDF", "PWF", "OSF"]:
        r = score_mode(df, mode)
        claims.append((f"{mode} precision", 1.000, r["precision"], 0, True))
        claims.append((f"{mode} recall", 1.000, r["recall"], 0, True))

    r_twf = score_mode(df, "TWF")
    claims.append(("TWF precision", 0.054, r_twf["precision"], 0.01, False))
    claims.append(("TWF recall", 0.935, r_twf["recall"], 0.02, False))

    # --- Root-cause accuracy at HIGH confidence ---
    correct = 0
    total_high = 0
    for _, row in df.iterrows():
        prob = float(engine.clf.predict_proba(
            row[FEATURE_COLUMNS].to_frame().T.astype(float)
        )[0, 1])
        verdict = assess(row, prob, engine.threshold)
        if verdict["confidence"] == "HIGH" and verdict["rootCause"] is not None:
            total_high += 1
            if verdict["rootCause"] in EXACT_MODES:
                correct += 1
    rc_accuracy = correct / total_high if total_high else 0.0
    claims.append(("Root-cause accuracy at HIGH confidence", 1.000, rc_accuracy, 0, True))

    # --- Demo case UDI 70 ---
    sig70 = engine.score_udi(70)
    claims.append(("UDI 70 severity", "CRITICAL", sig70["severity"], 0, True))
    claims.append(("UDI 70 rootCause", "OSF", sig70["rootCause"], 0, True))
    claims.append(("UDI 70 confidence", "HIGH", sig70["confidence"], 0, True))

    # --- Demo case UDI 78 ---
    sig78 = engine.score_udi(78)
    claims.append(("UDI 78 confidence", "CONFLICT", sig78["confidence"], 0, True))
    claims.append(("UDI 78 rootCause", None, sig78["rootCause"], 0, True))

    return claims


# --------------------------------------------------------------------------
# Runner
# --------------------------------------------------------------------------
def main() -> int:
    t0 = time.time()
    print("=" * 72)
    print("CLAIMS VERIFICATION — Judge-Proofing Artifact")
    print("=" * 72)
    print(f"Generated by: scripts/verify_claims.py")
    print(f"Source repo:  Cognizant_Hackathon")
    print()

    claims = build_claims()

    results = []
    all_pass = True

    for claim, expected, actual, tol, exact in claims:
        if exact:
            passed = actual == expected
        else:
            passed = abs(actual - expected) <= tol

        status = "PASS" if passed else "FAIL"
        if not passed:
            all_pass = False

        if isinstance(actual, float):
            actual_str = f"{actual:.4f}"
        else:
            actual_str = str(actual)

        if isinstance(expected, float):
            exp_str = f"{expected:.4f}"
        else:
            exp_str = str(expected)

        results.append((claim, expected, actual, status))
        print(f"  [{status}] {claim}")
        if not passed:
            print(f"           expected: {exp_str}, got: {actual_str}")

    elapsed = time.time() - t0
    print(f"\n{'=' * 72}")
    if all_pass:
        print(f"RESULT: ALL {len(results)} CLAIMS PASSED")
    else:
        failed = sum(1 for r in results if r[3] == "FAIL")
        print(f"RESULT: {failed}/{len(results)} CLAIMS FAILED")
    print(f"Time: {elapsed:.1f}s")
    print(f"{'=' * 72}")

    # --- Write verification report ---
    report_path = REPO_ROOT / "docs" / "verification_report.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Verification Report — Predictive Maintenance Agent",
        "",
        f"Generated by `scripts/verify_claims.py` on the `feat/dev4-platform` branch.",
        "",
        "## Claims Table",
        "",
        "| Claim | Expected | Actual | Status |",
        "|-------|----------|--------|--------|",
    ]
    for claim, expected, actual, status in results:
        if isinstance(actual, float):
            actual_str = f"{actual:.4f}"
        else:
            actual_str = str(actual)
        if isinstance(expected, float):
            exp_str = f"{expected:.4f}"
        else:
            exp_str = str(expected)
        lines.append(f"| {claim} | {exp_str} | {actual_str} | **{status}** |")

    lines.extend([
        "",
        "## Methodology",
        "",
        "- Dataset claims verified against committed `data/ai4i2020.csv`",
        "- Model metrics read from `docs/model_metrics.json` (produced by `src/train.py`)",
        "- Rules validation re-runs `validate_rules.score_mode` on all 10,000 rows",
        "- Root-cause accuracy computed by running `assess()` on every row and checking",
        "  that HIGH-confidence root causes are all in `EXACT_MODES` (OSF/PWF/HDF)",
        "- Demo cases scored via `Engine.score_udi()`",
        "",
        "## How to Reproduce",
        "",
        "```bash",
        "python src/train.py          # regenerate models (~30s)",
        "python src/validate_rules.py  # validate rules",
        "python scripts/verify_claims.py  # this script",
        "```",
        "",
        f"Total verification time: {elapsed:.1f}s",
    ])

    with open(report_path, "w") as f:
        f.write("\n".join(lines))
    print(f"\n  Wrote {report_path}")

    return 0 if all_pass else 1


if __name__ == "__main__":
    raise SystemExit(main())
